version: '3.4'

services:
  sourcingdb:
    container_name: sourcingdb
    restart: always
    volumes:
     - ${WEAPP_STORAGE_HOME}/site:/data/db 
     #- ./data:/data/db
    ports:
     - "27017:27017" 
  services.product:
    container_name: serviceProduct
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - "ProductDatabaseSettings: ConnectionStrings=mongodb://sourcingdb:27017"
    depends_on:
      - sourcingdb 
    volumes:
      - ${HOME}/.Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${HOME}/.ASP.NET/Https:/root/.aspnet/https:ro
    ports:
      - "7000:80"
